routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('books', 'BookController');

Route::resource('authors', 'AuthorController');

Route::resource('category', 'CategoryController');

Route::get('/dashboard', 'HomeController@dashboard')->name('home');

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Model\Author;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use App\Interfaces\BookRepositoryInterface;
use App\Model\Book;
use App\Http\Requests\BookRequest;
use Illuminate\Support\Collection;

/**
 * Class BooksController
 * @package App\Http\Controllers
 */
class BookController extends Controller
{
    /**
     * @var BookRepositoryInterface
     */
    private $repository;

    /**
     * BooksController constructor.
     * @param BookRepositoryInterface $bookRepository
     */
    public function __construct(BookRepositoryInterface $bookRepository)
    {
        $this->repository = $bookRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = $this->repository->all();
        return view('books.index', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $book = $this->repository->getEmptyModel();
        $authors = \App\Model\Author::all();
        $categories = \App\Model\Category::all();
        return view('books.create', compact('book', 'authors', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(BookRequest $request)
    {
        $this->repository->store($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $book = $this->repository->getOne($id);
        return view('books.single', compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = $this->repository->getOne($id);
        $authors = \App\Model\Author::all();
        $categories = \App\Model\Category::all();
        return view('books.edit', compact('book', 'authors', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update($id, BookRequest $request)
    {
        try {
            $book = $this->repository->getOne($id);
            $this->repository->update($book, $request->all());
        } catch (ModelNotFoundException $e) {
            return redirect('books');
        }

        return redirect('books');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->repository->delete($id);
        } catch (ModelNotFoundException $e) {
            return redirect('books');
        }

        return redirect('books');
    }
}

resources/views/books/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-body">
                        <form role="form"
                              action="{{ route('books.store', [], false) }}"
                              method="post" enctype="multipart/form-data">
                            @csrf

                            <div class="form-group">
                                <input type="text" class="form-control" id="title" name="title" placeholder="Title" value="" />
                                @if ($errors->has('title'))
                                    <div class="error">{{ $errors->first('title') }}</div>
                                @endif
                            </div>

                            <div class="form-grop">
                                <input type="file" class="filestyle" id="cover" name="cover">
                                @if ($errors->has('cover'))
                                    <div class="error">{{ $errors->first('cover') }}</div>
                                @endif
                            </div>

                            <select multiple id="authors" style="width:100%" name="authors[]">
                                @foreach($authors as $author)
                                    <option value="{{$author->id}}"
                                            >{{$author->first_name}} {{$author->last_name}}</option>
                                @endforeach
                            </select>
                            {{--<input id="selectedTags" type="hidden" name="tags" value="">--}}

                            <select multiple id="categories" style="width:100%" name="categories[]">
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                @endforeach
                            </select>

                            <br><br>
                            <input type="submit" value="Save">

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/books/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-body">
                        <form role="form"
                              action="{{ route('books.update', ['book' => $book->id], false) }}"
                              method="post" enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                            <div class="form-group">
                                <input type="text" class="form-control" id="title" name="title" placeholder="Title" value="{{ $book->title }}" />
                                @if ($errors->has('title'))
                                    <div class="error">{{ $errors->first('title') }}</div>
                                @endif
                            </div>
                            @if(!empty($book->cover))
                                <img src="{{ asset($book->cover) }}" alt="" style="max-width: 150px">
                            @endif

                            <div class="form-group">
                                <br>
                                <input type="file" class="filestyle" id="cover" name="cover">
                                @if ($errors->has('cover'))
                                    <div class="error">{{ $errors->first('cover') }}</div>
                                @endif
                            </div>

                            <select multiple id="authors" style="width:100%" name="authors[]">
                                @foreach($authors as $author)
                                    <option value="{{$author->id}}"
                                            {{ $book->isSelectedAuthor($author->id) }}>{{$author->first_name}} {{$author->last_name}}</option>
                                @endforeach
                                {{-- @if(old('status', $model->status) === $status) selected @endif --}}
                            </select>

                            <select multiple id="categories" style="width:100%" name="categories[]">
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}" {{ $book->isSelectedCategory($category->id) }}>{{$category->name}}</option>
                                @endforeach
                            </select>

                            <br> <br>
                            <input type="submit" value="Update">

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('headerScripts')
    <style>
        .select2-container--default .select2-selection--single {
            display: block;
            border-radius: 0;
            width: 100%;
            height: 34px;
            padding: 6px 12px;
            font-size: 14px;
            line-height: 1.42857143;
            color: #555;
            background-color: #fff;
            background-image: none;
            border: 1px solid #ccc;
            -webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
            box-shadow: inset 0 1px 1px rgba(0,0,0,.075);
            -webkit-transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
            transition: border-color ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
            transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s;
            transition: border-color ease-in-out .15s,box-shadow ease-in-out .15s,-webkit-box-shadow ease-in-out .15s;
        }
    </style>
@endsection

@section('footerScripts')
<script>
    $(document).ready(function () {
        var $authors = $('#authors');
        $authors.select2({
            tags: true,
        });

        $authors.on("select2:select", function (e) {
            var $electedTags = $('#selectedTags');
            var curVal = $electedTags.val();
            curVal = prepareSelect2(curVal);
            var item = {
                "id": e.params.data.id === e.params.data.text ? null : e.params.data.id,
                "select2Id": e.params.data.id,
                "name": e.params.data.text
            };
            curVal.push(item);
            $electedTags.val(JSON.stringify(curVal));
        });
        $authors.on("select2:unselect", function (e) {
            var $electedTags = $('#selectedTags');
            var curVal = $electedTags.val();
            curVal = prepareSelect2(curVal);
            curVal = curVal.filter(function (item) {
                return item['select2Id'] !== e.params.data.id;
            });
            $electedTags.val(JSON.stringify(curVal));
        });

        var prepareSelect2 = function (value) {
            if (value) {
                value = JSON.parse(value);
            }
            if (!Array.isArray(value)) {
                value = value ? new Array(value) : [];
            }

            return value;
        }
    });
</script>
@endsection

resources/views/books/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-body books-container">
                        @if(auth()->check() == true)
                            <a href="{{ route('books.create') }}" class="btn btn-success">Add book</a>
                        @endif
                        <div class="container">
                            <div class="row">
                                @foreach($books as $book)
                                    <a class="col-md-3" href="{{ route('books.show', ['id' => $book->id]) }}">
                                        <p>{{ $book->title }}</p>
                                        <img src="{{ $book->cover }}" alt="">
                                    </a>
                                @endforeach
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/books/single.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-body">
                        @if(auth()->check() == true)
                            <a href="{{ route('books.edit', ['id' => $book->id ]) }}" class="btn btn-success">Edit book</a>

                            <form role="form"
                                  action="{{ route('books.destroy', ['id' => $book->id], false) }}"
                                  method="post" enctype="multipart/form-data">
                                <div>
                                    @method('DELETE')
                                    @csrf
                                    <input type="submit" value="Delete" class="btn btn-danger">
                                </div>
                            </form>
                        @endif
                        <br> <br>
                        <div class="container">
                            <div class="row">
                                <div class="col-md-4">
                                    <img src="{{ asset($book->cover) }}" alt="">
                                </div>
                                <div class="col-md-8">
                                    <p>{{ $book->title }}</p>
                                    <p>
                                        @if(count($book->authors) == 1)
                                            Author:
                                        @elseif(count($book->authors) > 1)
                                            Authors:
                                        @endif

                                        @foreach($book->authors as $author)
                                            <span>{{ $author->first_name }} {{ $author->last_name }}</span>,
                                            @if (!$loop->last),@endif
                                        @endforeach
                                    </p>

                                    <p>
                                        @if(count($book->categories) == 1)
                                            Category:
                                        @elseif(count($book->categories) > 1)
                                            Categories:
                                        @endif

                                        @foreach($book->categories as $category)
                                            <span>{{ $category->name }} </span>
                                            @if (!$loop->last),@endif
                                        @endforeach
                                    </p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection