routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::resource('books', 'BookController');

Route::resource('authors', 'AuthorController');

Route::resource('category', 'CategoryController');

Route::get('/dashboard', 'HomeController@dashboard')->name('home');

app/Http/Controllers/AuthorController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AuthorRequest;
use App\Interfaces\AuthorRepositoryInterface;
use Illuminate\Database\Eloquent\ModelNotFoundException;

/**
 * Class AuthorController
 * @package App\Http\Controllers
 */
class AuthorController extends Controller
{

    /**
     * @var AuthorRepositoryInterface
     */
    private $repository;

    /**
     * AuthorController constructor.
     * @param AuthorRepositoryInterface $authorRepository
     */
    public function __construct(AuthorRepositoryInterface $authorRepository)
    {
        $this->repository = $authorRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $authors = $this->repository->all();
        return view('author.index', compact('authors'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $author = $this->repository->getEmptyModel();

        return view('author.create', compact('author'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param AuthorRequest $request
     */
    public function store(AuthorRequest $request)
    {
        $this->repository->store($request->all());
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $author = $this->repository->getOne($id);
        return view('author.single', compact('author'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $author = $this->repository->getOne($id);

        return view('author.edit', compact('author'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  AuthorRequest $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AuthorRequest $request, $id)
    {
        try {
            $author = $this->repository->getOne($id);
            $this->repository->update($author, $request->all());
        } catch (ModelNotFoundException $e) {
            return redirect('authors');
        }

        return redirect('authors');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $this->repository->delete($id);
        } catch (ModelNotFoundException $e) {
            return redirect('authors');
        }

        return redirect('authors');
    }
}

resources/views/author/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-body">
                        <form role="form"
                              action="{{ route('authors.store', [], false) }}"
                              method="post" enctype="multipart/form-data">
                            @csrf

                            <div class="form-group">
                                <input type="text" class="form-control" id="title" name="first_name" placeholder="First name" value="" />
                                @if ($errors->has('first_name'))
                                    <div class="error">{{ $errors->first('first_name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <input type="text" class="form-control" id="title" name="last_name" placeholder="Last name" value="" />
                                @if ($errors->has('last_name'))
                                    <div class="error">{{ $errors->first('last_name') }}</div>
                                @endif
                            </div>

                            <input type="submit" value="Save" class="btn btn-primary">

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/author/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-body">
                        <form role="form"
                              action="{{ route('authors.update', ['author' => $author->id], false) }}"
                              method="post" enctype="multipart/form-data">
                            @method('PUT')
                            @csrf

                            <div class="form-group">
                                <input type="text" class="form-control" id="title" name="first_name" placeholder="First name" value="{{ $author->first_name }}" />
                                @if ($errors->has('first_name'))
                                    <div class="error">{{ $errors->first('first_name') }}</div>
                                @endif
                            </div>

                            <div class="form-group">
                                <input type="text" class="form-control" id="title" name="last_name" placeholder="Last Name" value="{{ $author->last_name }}" />
                                @if ($errors->has('last_name'))
                                    <div class="error">{{ $errors->first('last_name') }}</div>
                                @endif
                            </div>

                            <input type="submit" value="Update" class="btn btn-primary">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/author/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-body books-container">
                        @if(auth()->check() == true)
                            <a href="{{ route('authors.create') }}" class="btn btn-success">Add author</a>
                        @endif
                        <div class="container">
                            <div class="row">
                                <ul>
                                @foreach($authors as $author)
                                    <li><a href="{{ route('authors.show', ['id' => $author->id]) }}">{{ $author->first_name }} {{ $author->last_name }}</a></li>
                                @endforeach
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/author/single.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-body">
                        @if(auth()->check() == true)
                            <a href="{{ route('authors.edit', ['id' => $author->id ]) }}" class="btn btn-success">Edit author</a>

                            <form role="form"
                                  action="{{ route('authors.destroy', ['author' => $author->id], false) }}"
                                  method="post" enctype="multipart/form-data">
                            <div>
                                @method('DELETE')
                                @csrf
                                <input type="submit" value="Delete" class="btn btn-danger">
                            </div>
                            </form>
                        @endif
                        <br> <br>
                        <div class="container">
                            <div class="row">

                                <div class="col-md-8">
                                    <p>{{ $author->first_name }} {{ $author->last_name }}</p>
                                    @if(count($author->books) > 0)
                                        Books:
                                    @endif
                                    @foreach($author->books as $book)
                                        <p><a href="{{ route('books.show', ['id' => $book->id]) }}">{{ $book->title }}</a></p>
                                    @endforeach
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection